### ISSUE TITLE
Issue on installation via composer

### ISSUE THREAD

**Issue by greggythefly** [atgp/factur-x#1]
When I do a "composer require atgp/factur-x" inside my projet I have the following errors (cf my composer.json content at the bottom)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install atgp/factur-x v1.0.1
    - Conclusion: remove setasign/fpdi 1.6.2
    - Installation request for atgp/factur-x ^1.0 -> satisfiable by atgp/factur-x[v1.0.0, v1.0.1].
    - Conclusion: don't install setasign/fpdi 1.6.2
    - atgp/factur-x v1.0.0 requires setasign/fpdi-fpdf ^2.0 -> satisfiable by setasign/fpdi-fpdf[v2.0.0, v2.1.0].
    - setasign/fpdi-fpdf v2.0.0 requires setasign/fpdi ^2.0 -> satisfiable by setasign/fpdi[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1].
    - setasign/fpdi-fpdf v2.1.0 requires setasign/fpdi ^2.1 -> satisfiable by setasign/fpdi[v2.1.0, v2.1.1].
    - Can only install one of: setasign/fpdi[v2.0.0, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.0.1, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.0.2, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.0.3, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.1.0, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.1.1, 1.6.2].
    - Installation request for setasign/fpdi (locked at 1.6.2) -> satisfiable by setasign/fpdi[1.6.2].

```json
{
  "name": "factomos",
  "description": "factomos",
  "license": "MIT",
  "config": {
    "preferred-install": "dist"
  },
  "authors": [
    {
      "name": "Fredrik Liljegren",
      "email": "fredrik.liljegren@textalk.se"
    }
  ],
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/copromatic/maileva"
    }
  ],
  "require": {
    "gocardless/gocardless-pro": "0.9.0",
    "wisembly/elephant.io": "~3.0",
    "ezyang/htmlpurifier": "^4.8",
    "spipu/html2pdf": "^4.6",
    "mpdf/mpdf": "^7.1",
    "nesbot/carbon": "^1.22",
    "copromatic/maileva": "dev-master",
    "knplabs/knp-snappy": "^1.0",
    "wildbit/postmark-php": "^2.5",
    "jjaffeux/postmark-inbound-php": ">=3.0",
    "stripe/stripe-php": "^6.17",
    "jenssegers/date": "^3.4"
  },
  "require-dev": {
    "phpunit/phpunit": "^5.7"
  }
}

```

**Comment by greggythefly** [comment]
J'ai trouvé le souci, mpdf utilise la version 1.6 de setasign/fpdi, ça n'est donc pas compatible

**Comment by greggythefly** [comment]
Pour info, il faut utiliser un fork de mpdf pour que cela fonctionne : 
```shell
composer config repositories.janslabon_mpdf_fpdi_update vcs https://github.com/JanSlabon/mpdf.git
composer require --prefer-source 'mpdf/mpdf:dev-FPDI-2-Update'
```

**Comment by lucas-gp** [comment]
En effet, j'ai essayé de voir si la librairie pouvait fonctionner avec FPDI en 1.6, mais ça implique plusieurs modifications : 
- Passer en public les fonctions _putresources / _putcatalog et _puttrailer de FdpiFacturx.php
- Modifier directement la librairie FDPI pour ajouter la fonction _put non présente en 1.6, qui permet d'écrire directement dans le fichier PDF (/vendor/setasign/fdpi/fdpi.php)

`/**
     * @inheritdoc
     */
    protected function _put($s, $newLine = true)
    {
        if ($newLine) {
            $this->buffer .= $s . "\n";
        } else {
            $this->buffer .= $s;
        }
    }`

Avec ces modifications cela fonctionne, mais vu que cela implique une modification de FDPI et que ça casse la compatibilité avec la version 2.0 de FDPI, je ne peux pas faire le correctif, mais vous pouvez essayer comme ça dans un premier temps

Et espérer que par la suite mpdf soit compatible avec FDPI 2.0 : https://github.com/mpdf/mpdf/issues/578

**Comment by lucas-gp** [comment]
> Pour info, il faut utiliser un fork de mpdf pour que cela fonctionne :
> 
> ```shell
> composer config repositories.janslabon_mpdf_fpdi_update vcs https://github.com/JanSlabon/mpdf.git
> composer require --prefer-source 'mpdf/mpdf:dev-FPDI-2-Update'
> ```

Parfait si il y a un fork avec FDPI 2.0
