### ISSUE TITLE
checkFacturxXsd returns true for wrong profiles if XML is valid

### ISSUE THREAD

**Issue by mahdiabderraouf** [atgp/factur-x#11]
## Bug description

the method ``checkFacturxXsd`` returns ``true`` for any wrong profile if the given XML is valid.

## How to reproduce ?

call the method ``checkFacturxXsd`` with a wrong profil and a valid XML.
```
$facturx = new Facturx();
$isXSDValid = $facturx->checkFacturxXsd($validXml, 'anywrongprofile');
echo (string) $isXSDValid; // "true"
```

## Solution

Detect profil automaticly only if the given profil is ``"autodetect"``. A [pull-request](https://github.com/atgp/factur-x/pull/10) has been created for the give solution.

**Comment by lucas-gp** [comment]
Pull request merged
Thanks
