### ISSUE TITLE
Could you validate your pull requests

### ISSUE THREAD

**Issue by SebastienLecocq** [atgp/factur-x#14]
Hello, 

I'm using this lib as it is recommended by FNFE MPE to manage factux files. But it is not compatible with the format 'extended'. I saw that another user submitted you two pull request with these improvements, but you didn't looked at them, as they are open since more than one year. Could you please have a look on them.

For the moment, I don't use lib anymore, and use the fork of this user to have a full compatibility.

Regards
Sebastien

**Comment by lucas-gp** [comment]
Hello,

Just tested and merged all pull request
Sorry I was busy and I forgot to check this repo

I'll try to be faster next time !

**Comment by SebastienLecocq** [comment]
Hi, great !

Is it possible to create a release version please, I'd like to update the package with composer ?

Regards

**Comment by lucas-gp** [comment]
Hello @SebastienLecocq 

Just created the release v1.0.3
