### ISSUE TITLE
Extended missing in FACTURX_PROFIL_TO_XMP

### ISSUE THREAD

**Issue by nathan-de-pachtere** [atgp/factur-x#15]
Hi,

I'm using your awesome code to generate facturX from PDF and xml (from easybill/zugferd-php).

Just missing this line to make it work with extended XML data.

```php
//Facturx.php

const FACTURX_PROFIL_TO_XMP = array(
        'minimum' => 'MINIMUM',
        'basicwl' => 'BASIC WL',
        'basic' => 'BASIC',
        'en16931' => 'EN 16931',
        'extended' => 'EXTENDED', //without this line the generateFacturxFromFiles function crash on line 340
    );
```

**Comment by lucas-gp** [comment]
@nathan-de-pachtere just pushed a fix for it, thanks for your feedback
#16 
Sorry missed your PR
