### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by wq9578** [atgp/factur-x#20]
Deprecated warning (using PHP 8.2.0):
```
PHP Deprecated:  Function utf8_encode() is deprecated in .../vendor/atgp/factur-x/src/Fpdi/FdpiFacturx.php on line 65
PHP Deprecated:  Function utf8_encode() is deprecated in .../vendor/atgp/factur-x/src/Fpdi/FdpiFacturx.php on line 133
```

**Comment by lucas-gp** [comment]
Hello,
Don't hesitate to make pull request to fix it :slightly_smiling_face:

**Comment by wq9578** [comment]
> Solution: Use the “mb_convert_encoding” function.

```
<?php

$utf8 = mb_convert_encoding("\xa5\xa7\xb5", 'UTF-8', 'ISO-8859-2'); // ISO-8859-2 -> UTF-8
$iso88592 = mb_convert_encoding($utf8, 'ISO-8859-2', 'UTF-8');      // UTF-8 -> ISO-8859-2
```
https://www.followchain.org/utf8-encode-decode-deprecated-php/

See also: https://lindevs.com/functions-utf8_encode-and-utf8_decode-are-deprecated-in-php-8-2

**Comment by crozet-magenta** [comment]
Hi @wq9578 It should be fixed with the new version, I don't have the warning anymore on my app
Thank you @lucas-gp for the merge
