### ISSUE TITLE
XMP not valid with https://services.fnfe-mpe.org/tools

### ISSUE THREAD

**Issue by pottiok** [atgp/factur-x#23]
Thanks for your work !
I'have created an invoice file with your test application, but the XMP metadata of the generated file are not valid on
https://services.fnfe-mpe.org/tools
see the reporting

[2023-5634.pdf](https://github.com/atgp/factur-x/files/11140866/2023-5634.pdf)

**Comment by LoickMEYER** [comment]
Have

**Comment by LoickMEYER** [comment]
Did you find a solution ?

**Comment by iizno** [comment]
@pottiok 
Did you find a solution ?

**Comment by benito103e** [comment]
@pottiok can you try with the last version of the library, I updated the XSD and the color profile.
