### ISSUE TITLE
Problèmes sur les schémas XSD (BasicWL et Basic)

### ISSUE THREAD

**Issue by julienagullo** [atgp/factur-x#25]
Bonjour,

J'ai relevé 2 problèmes sur les schémas XSD des profils Basic WL et Basic selon la documentation 1.0.06 du FNFE :

BT-20 : Description des conditions de paiement
La description des conditions de paiement doit figurer sur les profils BasicWL et Basic.
![facturx_bt-20](https://github.com/atgp/factur-x/assets/50801123/07ad47ae-923a-4714-90ea-48fbce2f4f62)

BT-148-00
Le prix unitaire brut de la ligne de l'article doit figurer sur le profil Basic.
![facturx_bt-148](https://github.com/atgp/factur-x/assets/50801123/06e54c99-5922-4dc6-a26d-9c230d6b94ac)

Merci pour votre travail,

Bien cordialement

**Comment by benito103e** [comment]
Bonjour Julien,
J'ai créé la PR #26 pour maj les XSD
Bien cordialement.
