### ISSUE TITLE
Extract Factur-X XML from a PDF :: not working 

### ISSUE THREAD

**Issue by vivek-iflair167** [atgp/factur-x#3]
Hello @lucas-gp 
can you elaborate which type of PDF should i use ?
can you provide a **sample PDF for XML generation**.
thanks in advance..
#factur-x #pdf #Factur-X-XML

**Comment by lucas-gp** [comment]
Hello @vivek-iflair167 

You can use any Factur-X PDF
You can find example from official Factur-X webesite, here : http://fnfe-mpe.org/factur-x/factur-x_en/
Download the Zip and get any Factur-X PDF example
